# Generated by Django 2.2.5 on 2020-04-23 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('city_description', models.TextField()),
                ('city_banner_image', models.TextField()),
                ('city_logo', models.TextField()),
                ('city_thumbnail', models.TextField()),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField()),
                ('city_ranking', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('heading1', models.TextField()),
                ('heading2', models.TextField()),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_keyword', models.TextField()),
                ('meta_description', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('is_enabled', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('country_code', models.CharField(max_length=500)),
                ('currency_symbol', models.TextField(max_length=500)),
                ('banner_image', models.TextField()),
                ('country_logo', models.TextField(max_length=500)),
                ('country_thumbnail', models.TextField()),
                ('description', models.TextField()),
                ('country_ranking', models.PositiveIntegerField()),
                ('isfeatured', models.BooleanField()),
                ('heading1', models.TextField()),
                ('heading2', models.TextField()),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_keyword', models.TextField()),
                ('meta_description', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.CharField(max_length=500)),
                ('title', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('distance_from_city_center', models.FloatField(default=0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField()),
                ('isfeatured', models.BooleanField()),
                ('numbers_of_beds', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('property_type', models.CharField(max_length=500)),
                ('rating', models.FloatField()),
                ('base_currency_code', models.CharField(max_length=500)),
                ('whybook', models.TextField()),
                ('payment_procedure', models.TextField()),
                ('is_enabled', models.IntegerField(default=1)),
                ('ispropertyextraOrdinary', models.IntegerField(default=1)),
                ('propertylistingorder', models.IntegerField()),
                ('property_offers', models.TextField()),
                ('property_images', models.TextField()),
                ('heading1', models.TextField()),
                ('heading2', models.TextField()),
                ('meta_title', models.TextField()),
                ('meta_keywords', models.TextField()),
                ('meta_description', models.TextField()),
                ('room_categories', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accomodation.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accomodation.Country')),
            ],
            options={
                'db_table': 'property',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('enable_cancellation', models.BooleanField()),
                ('cancellation_description', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('banner_image', models.TextField()),
                ('logo', models.TextField()),
                ('thumbnail', models.TextField()),
                ('has_campus', models.BooleanField(max_length=500)),
                ('campus_detail', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.IntegerField(default=1)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('heading1', models.TextField()),
                ('heading2', models.TextField()),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_keyword', models.TextField()),
                ('meta_description', models.TextField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accomodation.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accomodation.Country')),
            ],
            options={
                'db_table': 'university',
            },
        ),
        migrations.CreateModel(
            name='ProviderCity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accomodation.City')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_city', to='student_accomodation.Provider')),
            ],
            options={
                'db_table': 'provider_city',
            },
        ),
        migrations.CreateModel(
            name='PropertyUniversity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accomodation.Property')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accomodation.University')),
            ],
            options={
                'db_table': 'property_university',
            },
        ),
        migrations.CreateModel(
            name='PropertyFacility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facilities_category', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accomodation.Facility')),
                ('property_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_facility', to='student_accomodation.Property')),
            ],
            options={
                'db_table': 'property_facility',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accomodation.Provider'),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_code', models.CharField(max_length=500)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'currency_code',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='currency_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_accomodation.Currency'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accomodation.Country'),
        ),
    ]
